name: safence
description: A new Flutter project
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  provider: ^6.1.5
  flutter_contacts: ^1.1.9+2
  call_log: ^5.0.0
  phone_state: ^1.0.4          
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  http: ^0.13.6
  flutter_secure_storage: ^9.2.4
  jwt_decode: ^0.3.1
  flutter_sms_inbox: ^1.0.4
  firebase_core: ^3.15.2
  firebase_storage: ^12.4.10
  flutter_dotenv: ^5.1.0
  firebase_auth: 5.7.0
  cloud_firestore: 5.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/navbar/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 200